

import { PlanningIcon, RiskIcon, AgentIcon, ScheduleIcon, BudgetIcon, AssistantIcon, StructureIcon, KpiIcon, SCurveIcon, DocumentIcon } from './components/Shared.js';

export const AppView = Object.freeze({
  Home: 'home',
  About: 'about',
  Contact: 'contact',
  Pricing: 'pricing',
  Dashboard: 'dashboard', 
  Admin: 'admin', 
  Settings: 'settings', // New User Settings View
  Terms: 'terms',
  Privacy: 'privacy',
});

export const Language = Object.freeze({
  EN: 'en',
  AR: 'ar',
});

export const DASHBOARD_VIEWS = [
    { id: 'assistant', titleKey: 'dashboardAssistant', icon: AssistantIcon },
    { id: 'consultingPlan', titleKey: 'dashboardConsultingPlan', icon: DocumentIcon },
    { id: 'planning', titleKey: 'dashboardPlanning', icon: PlanningIcon },
    { id: 'scheduling', titleKey: 'dashboardScheduling', icon: ScheduleIcon },
    { id: 'kpis', titleKey: 'dashboardKpis', icon: KpiIcon },
    { id: 'scurve', titleKey: 'dashboardSCurve', icon: SCurveIcon },
    { id: 'structure', titleKey: 'dashboardStructure', icon: StructureIcon },
    { id: 'risk', titleKey: 'dashboardRisk', icon: RiskIcon },
    { id: 'budget', titleKey: 'dashboardBudget', icon: BudgetIcon },
    { id: 'agents', titleKey: 'dashboardAgents', icon: AgentIcon },
];

export const i18n = {
  [Language.EN]: {
    title: "PM Roadmap",
    navHome: "Home",
    navFeatures: "Features",
    navIndustries: "Industries",
    navPricing: "Pricing",
    navContact: "Contact Us",
    navSupport: "Support",
    navTerms: "Terms & Conditions",
    navPrivacy: "Privacy Policy",
    navDashboard: "Dashboard",
    navAdmin: "Admin Dashboard",
    navSettings: "Settings",
    // Home - Hero
    homeHeroTitle: "Revolutionizing Project & Construction Management with AI",
    homeHeroDescription: "Cutting-edge AI capabilities that significantly transform how construction and project teams collaborate and work together efficiently.",
    getStarted: "Get Started",
    // Home - Why Choose Us
    whyChooseUsTitle: "Why Choose Our Platform?",
    whyChoose1Title: "AI-Powered Planning",
    whyChoose1Desc: "Generate project charters, WBS, and schedules automatically with intelligent algorithms.",
    whyChoose2Title: "Intelligent Risk Control",
    whyChoose2Desc: "Predict, detect, and mitigate risks across all projects with real-time monitoring.",
    whyChoose3Title: "Smart Cost Estimation",
    whyChoose3Desc: "AI-driven forecasts with real-time anomaly detection to prevent budget overruns.",
    whyChoose4Title: "Construction AI Agents",
    whyChoose4Desc: "Site monitoring, digital twins, and compliance automation powered by AI.",
    // Home - Platform Capabilities
    capabilitiesTitle: "Platform Capabilities",
    capabilitiesDescription: "Comprehensive tools powered by advanced AI technology to streamline every phase of your project efficiently.",
    capability1Title: "AI Planning Engine",
    capability1Desc: "Automatically turn objectives into detailed project plans with WBS, milestones, and resource allocation.",
    capability2Title: "Dynamic Scheduling",
    capability2Desc: "Adapt schedules instantly when delays occur, with real-time updates that keep dependencies aligned.",
    capability3Title: "AI Agents",
    capability3Desc: "Autonomous assistants that handle meeting notes, vendor offers, and compliance checks.",
    capability4Title: "Risk Intelligence Dashboard",
    capability4Desc: "Detect risks early as AI scans project data, highlights issues, and suggests mitigation strategies.",
    capability5Title: "Budget & Cost Forecasting",
    capability5Desc: "Prevent overruns with AI-driven forecasts, anomaly detection, and proactive budget insights.",
    // Home - Industries
    industriesTitle: "Tailored for Every Industry",
    industriesDescription: "From construction sites to enterprise platforms and government projects.",
    industry1Title: "Construction Projects",
    industry1Desc: "AI-driven cost estimation, drone/camera integration, contract/vendor AI.",
    industry1Feature1: "Accurate forecasts of labor, materials, and equipment.",
    industry1Feature2: "Real-time site monitoring and progress tracking.",
    industry1Feature3: "Automated offer generation and compliance checks.",
    industry2Title: "Enterprise Platforms",
    industry2Desc: "Multi-project dashboards, effective governance, KPI optimization.",
    industry2Feature1: "Unified visibility across all initiatives.",
    industry2Feature2: "Standardized processes with AI-driven oversight.",
    industry2Feature3: "Intelligent tracking and improvement of performance.",
    industry3Title: "Government & Smart Cities",
    industry3Desc: "Future-ready infrastructure and policy management.",
    industry3Feature1: "Virtual models for planning and scenario testing.",
    industry3Feature2: "Automated checks against regulations and standards.",
    industry3Feature3: "AI-driven comparisons for efficiency and performance.",
    // Welcome Modal
    welcomeTitle: "Welcome to PM Roadmap",
    welcomeDescription: "The future of Project & Construction Management starts here. Let's build better, together.",
    welcomeStart: "Explore Platform",
    welcomeAuth: "Login / Register",
    // About Us
    aboutTitle: "About PM Roadmap",
    aboutVisionTitle: "Our Vision",
    aboutVisionText: "To build the future of project management, where AI-driven intelligence empowers teams to deliver complex projects with unprecedented efficiency, accuracy, and foresight.",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "Our mission is to equip project and construction managers with cutting-edge AI tools that automate planning, mitigate risks, and optimize costs, turning ambitious plans into successful realities.",
    // Contact Us
    contactTitle: "Get in touch",
    contactDescription: "Have a question about our platform or want a custom demo? We're here to help.",
    // Pricing
    pricingTitle: "Choose Your Plan",
    pricingDescription: "Unlock the full power of AI for your projects and boost your team's productivity. Choose the plan that's right for you.",
    monthly: "Monthly",
    yearly: "Yearly",
    save20: "Save 20%",
    mostPopular: "Most Popular",
    choosePlan: "Choose Plan",
    // Payment Modal
    paymentTitle: "Complete Your Purchase",
    paymentFor: "You are subscribing to the",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date (MM/YY)",
    cvc: "CVC",
    payNow: "Pay Now",
    processingPayment: "Processing Payment...",
    paymentSuccess: "Payment Successful!",
    welcomeAboard: "Welcome aboard! You now have full access to the PM Roadmap platform.",
    // Dashboard & AI Assistant (formerly SciGenius Chat)
    assistantTitle: "AI Project Assistant",
    assistantDescription: "Your personal AI assistant. Ask about project status, generate reports, or analyze risks.",
    searchWeb: "Search on the web",
    attachFile: "Attach File",
    thinking: "AI Assistant is thinking...",
    sources: "Sources",
    dashboardAssistant: "AI Assistant",
    dashboardConsultingPlan: "Project Plan",
    dashboardPlanning: "Planning",
    dashboardScheduling: "Scheduling",
    dashboardStructure: "Structure",
    dashboardRisk: "Risk Control",
    dashboardBudget: "Budget",
    dashboardAgents: "AI Agents",
    dashboardKpis: "KPIs",
    dashboardSCurve: "S-Curve",
    // General
    errorOccurred: "An error occurred. Please try again.",
    connectWithUs: "Connect with us",
    history: "History",
    clearHistory: "Clear History",
    noHistory: "No history yet.",
    premiumFeature: "Premium",
    // Auth
    loginRegister: "Login",
    login: "Login",
    register: "Register",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    logout: "Logout",
    authRequiredTitle: "Authentication Required",
    authRequiredMessage: "Access Restricted. Please create a free account to continue exploring the dashboard.",
    upgradeRequiredTitle: "Upgrade to Unlock This Feature",
    upgradeRequiredMessage: "This is a premium feature. Please upgrade your plan to get full access and enhance your project management capabilities.",
    viewPlans: "View Plans",
    noCreditCardRequired: "No credit card required for free plan",
    signInWithGoogle: "Sign in with Google",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    authRegistrationDisclaimer_p1: "By creating an account, you agree to our",
    authRegistrationDisclaimer_terms: "Terms of Service",
    authRegistrationDisclaimer_p2: "and",
    authRegistrationDisclaimer_privacy: "Privacy Policy",
    authRegistrationDisclaimer_p3: ".",
    registrationSuccess: "Registration successful! You can now log in.",
    errorInvalidCredentials: "Invalid email or password.",
    errorFullNameRequired: "Full name is required.",
    errorInvalidEmail: "Please enter a valid email address.",
    errorPasswordLength: "Password must be at least 8 characters long.",
    errorPasswordMismatch: "Passwords do not match.",
    errorUserExists: "An account with this email already exists.",
  },
  [Language.AR]: {
    title: "خارطة طريق المشروع",
    navHome: "الرئيسية",
    navFeatures: "الميزات",
    navIndustries: "الصناعات",
    navPricing: "الأسعار",
    navContact: "اتصل بنا",
    navSupport: "الدعم",
    navTerms: "الشروط والأحكام",
    navPrivacy: "سياسة الخصوصية",
    navDashboard: "لوحة التحكم",
    navAdmin: "لوحة الإدارة",
    navSettings: "الإعدادات",
    // Home - Hero
    homeHeroTitle: "ثورة في إدارة المشاريع والإنشاءات بالذكاء الاصطناعي",
    homeHeroDescription: "قدرات ذكاء اصطناعي متطورة تغير بشكل جذري كيفية تعاون فرق البناء والمشاريع وعملها معًا بكفاءة.",
    getStarted: "ابدأ الآن",
    // Home - Why Choose Us
    whyChooseUsTitle: "لماذا تختار منصتنا؟",
    whyChoose1Title: "تخطيط مدعوم بالذكاء الاصطناعي",
    whyChoose1Desc: "أنشئ مواثيق المشاريع، وهياكل تقسيم العمل، والجداول الزمنية تلقائيًا باستخدام خوارزميات ذكية.",
    whyChoose2Title: "تحكم ذكي في المخاطر",
    whyChoose2Desc: "تنبأ بالمخاطر واكتشفها وخفف من حدتها في جميع المشاريع من خلال المراقبة في الوقت الفعلي.",
    whyChoose3Title: "تقدير ذكي للتكاليف",
    whyChoose3Desc: "توقعات مدفوعة بالذكاء الاصطناعي مع اكتشاف فوري للحالات الشاذة لمنع تجاوز الميزانية.",
    whyChoose4Title: "وكلاء الذكاء الاصطناعي للإنشاءات",
    whyChoose4Desc: "مراقبة الموقع، والتوائم الرقمية، وأتمتة الامتثال مدعومة بالذكاء الاصطناعي.",
    // Home - Platform Capabilities
    capabilitiesTitle: "قدرات المنصة",
    capabilitiesDescription: "أدوات شاملة مدعومة بتقنية الذكاء الاصطناعي المتقدمة لتبسيط كل مرحلة من مراحل مشروعك بكفاءة.",
    capability1Title: "محرك التخطيط الذكي",
    capability1Desc: "حوّل الأهداف تلقائيًا إلى خطط مشاريع مفصلة مع هياكل تقسيم العمل، والمعالم، وتخصيص الموارد.",
    capability2Title: "جدولة ديناميكية",
    capability2Desc: "كيّف الجداول الزمنية فورًا عند حدوث تأخير، مع تحديثات في الوقت الفعلي تحافظ على توافق التبعيات.",
    capability3Title: "وكلاء الذكاء الاصطناعي",
    capability3Desc: "مساعدون مستقلون يتولون ملاحظات الاجتماعات وعروض الموردين وفحوصات الامتثال.",
    capability4Title: "لوحة معلومات ذكاء المخاطر",
    capability4Desc: "اكتشف المخاطر مبكرًا حيث يقوم الذكاء الاصطناعي بمسح بيانات المشروع وتسليط الضوء على المشكلات الحرجة.",
    capability5Title: "توقع الميزانية والتكاليف",
    capability5Desc: "امنع التجاوزات قبل حدوثها من خلال التوقعات المدفوعة بالذكاء الاصطناعي واكتشاف الحالات الشاذة.",
    // Home - Industries
    industriesTitle: "مصممة لكل صناعة",
    industriesDescription: "من مواقع البناء إلى منصات المؤسسات والمشاريع الحكومية.",
    industry1Title: "مشاريع البناء",
    industry1Desc: "تقدير التكاليف المدفوع بالذكاء الاصطناعي، تكامل الطائرات بدون طيار/الكاميرات، الذكاء الاصطناعي للعقود/الموردين.",
    industry1Feature1: "توقعات دقيقة للعمالة والمواد والمعدات.",
    industry1Feature2: "مراقبة الموقع وتتبع التقدم في الوقت الفعلي.",
    industry1Feature3: "إنشاء العروض التلقائي وفحوصات الامتثال.",
    industry2Title: "منصات المؤسسات",
    industry2Desc: "لوحات معلومات متعددة المشاريع، حوكمة فعالة، تحسين مؤشرات الأداء الرئيسية.",
    industry2Feature1: "رؤية موحدة عبر جميع المبادرات.",
    industry2Feature2: "عمليات موحدة مع إشراف مدفوع بالذكاء الاصطناعي.",
    industry2Feature3: "تتبع ذكي وتحسين الأداء.",
    industry3Title: "الحكومة والمدن الذكية",
    industry3Desc: "بنية تحتية جاهزة للمستقبل وإدارة السياسات.",
    industry3Feature1: "نماذج افتراضية للتخطيط واختبار السيناريوهات.",
    industry3Feature2: "فحوصات آلية مقابل اللوائح والمعايير.",
    industry3Feature3: "مقارنات مدفوعة بالذكاء الاصطناعي لتتبع الكفاءة.",
    // Welcome Modal
    welcomeTitle: "مرحباً بك في خارطة طريق المشروع",
    welcomeDescription: "مستقبل إدارة المشاريع والإنشاءات يبدأ هنا. لنبني بشكل أفضل، معًا.",
    welcomeStart: "استكشف المنصة",
    welcomeAuth: "تسجيل الدخول / إنشاء حساب",
    // About Us
    aboutTitle: "عن خارطة طريق المشروع",
    aboutVisionTitle: "رؤيتنا",
    aboutVisionText: "بناء مستقبل إدارة المشاريع، حيث يمكّن الذكاء الاصطناعي الفرق من إنجاز المشاريع المعقدة بكفاءة ودقة وبصيرة غير مسبوقة.",
    aboutMissionTitle: "مهمتنا",
    aboutMissionText: "مهمتنا هي تزويد مديري المشاريع والإنشاءات بأدوات ذكاء اصطناعي متطورة تعمل على أتمتة التخطيط وتخفيف المخاطر وتحسين التكاليف، وتحويل الخطط الطموحة إلى حقائق ناجحة.",
    // Contact Us
    contactTitle: "تواصل معنا",
    contactDescription: "هل لديك سؤال حول منصتنا أو تريد عرضًا توضيحيًا مخصصًا؟ نحن هنا للمساعدة.",
    // Pricing
    pricingTitle: "اختر خطتك",
    pricingDescription: "أطلق العنان للقوة الكاملة للذكاء الاصطناعي لمشاريعك وعزز إنتاجية فريقك. اختر الخطة المناسبة لك.",
    monthly: "شهرياً",
    yearly: "سنوياً",
    save20: "وفر 20%",
    mostPopular: "الأكثر شيوعاً",
    choosePlan: "اختر الخطة",
    // Payment Modal
    paymentTitle: "أكمل عملية الشراء",
    paymentFor: "أنت على وشك الاشتراك في خطة",
    cardNumber: "رقم البطاقة",
    expiryDate: "تاريخ انتهاء الصلاحية (MM/YY)",
    cvc: "CVC",
    payNow: "ادفع الآن",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تم الدفع بنجاح!",
    welcomeAboard: "أهلاً بك! لديك الآن وصول كامل إلى منصة خارطة طريق المشروع.",
    // Dashboard & AI Assistant
    assistantTitle: "مساعد المشاريع الذكي",
    assistantDescription: "مساعدك الشخصي الذكي. اسأل عن حالة المشروع، أو أنشئ تقارير، أو حلل المخاطر.",
    searchWeb: "البحث في الويب",
    attachFile: "إرفاق ملف",
    thinking: "المساعد الذكي يفكر...",
    sources: "المصادر",
    dashboardAssistant: "مساعد الذكاء الاصطناعي",
    dashboardConsultingPlan: "خطة المشروع",
    dashboardPlanning: "التخطيط",
    dashboardScheduling: "الجدولة",
    dashboardStructure: "الهيكل",
    dashboardRisk: "إدارة المخاطر",
    dashboardBudget: "الميزانية",
    dashboardAgents: "الوكلاء الأذكياء",
    dashboardKpis: "مؤشرات الأداء",
    dashboardSCurve: "منحنى S",
    // General
    errorOccurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    connectWithUs: "تواصل معنا",
    history: "السجل",
    clearHistory: "مسح السجل",
    noHistory: "لا يوجد سجل حتى الآن.",
    premiumFeature: "بريميوم",
    // Auth
    loginRegister: "تسجيل الدخول",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    logout: "تسجيل الخروج",
    authRequiredTitle: "تسجيل الدخول مطلوب",
    authRequiredMessage: "الوصول مقيد. يرجى إنشاء حساب مجاني لمواصلة استكشاف لوحة التحكم.",
    upgradeRequiredTitle: "قم بالترقية لفتح هذه الميزة",
    upgradeRequiredMessage: "هذه ميزة مدفوعة. يرجى ترقية خطتك للحصول على وصول كامل وتعزيز قدرات إدارة المشاريع لديك.",
    viewPlans: "عرض الخطط",
    noCreditCardRequired: "لا حاجة لبطاقة ائتمان للخطة المجانية",
    signInWithGoogle: "تسجيل الدخول باستخدام جوجل",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    authRegistrationDisclaimer_p1: "بإنشاء حساب، فإنك توافق على",
    authRegistrationDisclaimer_terms: "شروط الخدمة",
    authRegistrationDisclaimer_p2: "و",
    authRegistrationDisclaimer_privacy: "سياسة الخصوصية",
    authRegistrationDisclaimer_p3: ".",
    registrationSuccess: "تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.",
    errorInvalidCredentials: "بريد إلكتروني أو كلمة مرور غير صالحة.",
    errorFullNameRequired: "الاسم الكامل مطلوب.",
    errorInvalidEmail: "الرجاء إدخال عنوان بريد إلكتروني صالح.",
    errorPasswordLength: "يجب أن لا تقل كلمة المرور عن 8 أحرف.",
    errorPasswordMismatch: "كلمتا المرور غير متطابقتين.",
    errorUserExists: "يوجد حساب بهذا البريد الإلكتروني بالفعل.",
  },
};

export const PRICING_PLANS = [
  {
    id: 'premium',
    name: { en: 'Pro', ar: 'الاحترافية' },
    isPopular: true,
    monthly: {
      price: { en: '$0', ar: '٠$' },
      period: { en: '/user/month (Limited Time Offer)', ar: '/مستخدم/شهر (عرض لفترة محدودة)' },
    },
    yearly: null,
    features: [
      { en: 'All services are free for a limited time!', ar: 'جميع الخدمات مجانية لفترة محدودة!' },
      { en: 'Unlimited projects', ar: 'مشاريع غير محدودة' },
      { en: 'Advanced AI Planning & Scheduling', ar: 'تخطيط وجدولة متقدمة بالذكاء الاصطناعي' },
      { en: 'Intelligent Risk Control & Mitigation', ar: 'تحكم ذكي في المخاطر وتخفيفها' },
      { en: 'Smart Cost Estimation & Forecasting', ar: 'تقدير وتوقع ذكي للتكاليف' },
      { en: 'Construction AI Agents', ar: 'وكلاء الذكاء الاصطناعي للإنشاءات' },
      { en: 'Priority support', ar: 'دعم ذو أولوية' },
    ],
    buttonTextKey: 'getStarted',
  },
   {
    id: 'enterprise',
    name: { en: 'Enterprise', ar: 'المؤسسات' },
    isPopular: false,
    monthly: {
      price: { en: 'Custom', ar: 'مخصص' },
      period: { en: '', ar: '' },
    },
    features: [
      { en: 'Includes all current Pro features', ar: 'يشمل جميع ميزات Pro الحالية' },
      { en: 'Multi-project dashboards', ar: 'لوحات معلومات متعددة المشاريع' },
      { en: 'Dedicated account manager', ar: 'مدير حساب مخصص' },
      { en: 'On-premise deployment option', ar: 'خيار النشر المحلي' },
    ],
    buttonTextKey: 'navContact',
  },
];